name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Build
        run: |
          flutter pub get
          flutter build linux --release
          cd build/linux/x64/release/bundle
          tar -czf ../../../../../labwcchanger-linux-x86_64.tar.gz *
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: labwcchanger-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}